### ISSUE TITLE
Various runtime errors in docker build

### ISSUE THREAD

**Issue by DarkRider1768** [mjtrangoni/flexlm_exporter#12]
### Host operating system: output of `uname -a`
docker
### flexlm_exporter version: output of `flexlm_exporter --version`

current, docker
### flexlm_exporter command line flags and relevant YAML configuration file information

["--path.lmutil=/usr/bin/flexlm/lmutil", "--path.config=/config/licenses.yml"]
licenses:
  - name: app2
    license_server: 27000@etv*****.*****.ad
    #features_to_include: feature5,feature30
    monitor_users: True
    monitor_reservations: True
### Are you running flexlm_exporter in Docker?
yes
### What did you do that produced an error?
absolutely nothing, it does it on it's own...
### What did you expect to see?
nothing, it doesn't output to the foreground unless there is an error, right?
### What did you see instead?
Several errors depending on when I ran it. The other I noticed was "Assignment to entry in nil map". This is the most recent:
```
flexlm_exporter_1           | fatal error: concurrent map writes
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 3422 [running]:
flexlm_exporter_1           | runtime.throw(0x944ea1, 0x15)
flexlm_exporter_1           |   /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc00024f6d8 sp=0xc00024f6a8 pc=0x42c222
flexlm_exporter_1           | runtime.mapassign_faststr(0x8a4320, 0xc000524150, 0xc000480cc4, 0xd, 0xc00007f8e8)
flexlm_exporter_1           |   /usr/local/go/src/runtime/map_faststr.go:199 +0x3da fp=0xc00024f740 sp=0xc00024f6d8 pc=0x41270a
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.parseLmstatLicenseInfoFeature(0xc000423000, 0x174, 0x200, 0xc00052a4e0, 0x3, 0x3)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:212 +0x761 fp=0xc00024f8c8 sp=0xc00024f740 pc=0x82e931
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).getLmstatLicensesInfo(0xc0000aca40, 0xc00008bda0, 0x0, 0x0)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:312 +0xa9b fp=0xc00024fde0 sp=0xc00024f8c8 pc=0x82fb1b
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).Update(0xc0000aca40, 0xc00008bda0, 0xd3afa0, 0x43e6d9)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat.go:87 +0xce fp=0xc00024fe48 sp=0xc00024fde0 pc=0x82b1ce
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.execute(0x93b921, 0x6, 0x9c4060, 0xc0000aca40, 0xc00008bda0)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:128 +0x7e fp=0xc00024ff78 sp=0xc00024fe48 pc=0x82a24e
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect.func1(0xc00008bda0, 0xc00019cdc0, 0x93b921, 0x6, 0x9c4060, 0xc0000aca40)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:119 +0x53 fp=0xc00024ffb0 sp=0xc00024ff78 pc=0x830703
flexlm_exporter_1           | runtime.goexit()
flexlm_exporter_1           |   /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00024ffb8 sp=0xc00024ffb0 pc=0x45b541
flexlm_exporter_1           | created by github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:118 +0x109
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 1 [IO wait]:
flexlm_exporter_1           | internal/poll.runtime_pollWait(0x7fe3848f2f00, 0x72, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/runtime/netpoll.go:173 +0x66
flexlm_exporter_1           | internal/poll.(*pollDesc).wait(0xc0001a6918, 0x72, 0xc0000ac000, 0x0, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
flexlm_exporter_1           | internal/poll.(*pollDesc).waitRead(0xc0001a6918, 0xffffffffffffff00, 0x0, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
flexlm_exporter_1           | internal/poll.(*FD).Accept(0xc0001a6900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
flexlm_exporter_1           | net.(*netFD).accept(0xc0001a6900, 0x40bb0f, 0xc0001ba280, 0xa0)
flexlm_exporter_1           |   /usr/local/go/src/net/fd_unix.go:238 +0x42
flexlm_exporter_1           | net.(*TCPListener).accept(0xc0001901f0, 0xc0004abc10, 0x8785644e, 0xf17e90de0ff0bfe4)
flexlm_exporter_1           |   /usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
flexlm_exporter_1           | net.(*TCPListener).AcceptTCP(0xc0001901f0, 0xc0004abc38, 0x48abe6, 0x5c4fb16d)
flexlm_exporter_1           |   /usr/local/go/src/net/tcpsock.go:247 +0x47
flexlm_exporter_1           | net/http.tcpKeepAliveListener.Accept(0xc0001901f0, 0xc0004abc88, 0x18, 0xc000000300, 0x680675)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:3232 +0x2f
flexlm_exporter_1           | net/http.(*Server).Serve(0xc00018b040, 0x9c9200, 0xc0001901f0, 0x0, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:2826 +0x22f
flexlm_exporter_1           | net/http.(*Server).ListenAndServe(0xc00018b040, 0xc00018b040, 0x2)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:2764 +0xb6
flexlm_exporter_1           | net/http.ListenAndServe(0x93a536, 0x5, 0x0, 0x0, 0x1, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:3004 +0x74
flexlm_exporter_1           | main.main()
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/flexlm_exporter.go:123 +0xae1
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 3443 [semacquire]:
flexlm_exporter_1           | sync.runtime_Semacquire(0xc000084c54)
flexlm_exporter_1           |   /usr/local/go/src/runtime/sema.go:56 +0x39
flexlm_exporter_1           | sync.(*WaitGroup).Wait(0xc000084c54)
flexlm_exporter_1           |   /usr/local/go/src/sync/waitgroup.go:130 +0x64
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1(0xc000084c54, 0xc00008b260)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:427 +0x2b
flexlm_exporter_1           | created by github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:426 +0x265
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 3452 [IO wait]:
flexlm_exporter_1           | internal/poll.runtime_pollWait(0x7fe3848f2880, 0x72, 0xc00015ee58)
flexlm_exporter_1           |   /usr/local/go/src/runtime/netpoll.go:173 +0x66
flexlm_exporter_1           | internal/poll.(*pollDesc).wait(0xc0001a6118, 0x72, 0xffffffffffffff00, 0x9c5280, 0xcfc440)
flexlm_exporter_1           |   /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
flexlm_exporter_1           | internal/poll.(*pollDesc).waitRead(0xc0001a6118, 0xc000553700, 0x1, 0x1)
flexlm_exporter_1           |   /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
flexlm_exporter_1           | internal/poll.(*FD).Read(0xc0001a6100, 0xc0005537b1, 0x1, 0x1, 0x0, 0x0, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
flexlm_exporter_1           | net.(*netFD).Read(0xc0001a6100, 0xc0005537b1, 0x1, 0x1, 0x80445f, 0xc000111318, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/net/fd_unix.go:202 +0x4f
flexlm_exporter_1           | net.(*conn).Read(0xc0000882c0, 0xc0005537b1, 0x1, 0x1, 0x0, 0x0, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/net/net.go:177 +0x68
flexlm_exporter_1           | net/http.(*connReader).backgroundRead(0xc0005537a0)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:676 +0x5a
flexlm_exporter_1           | created by net/http.(*connReader).startBackgroundRead
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:672 +0xd2
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 3444 [semacquire]:
flexlm_exporter_1           | sync.runtime_Semacquire(0xc000084c68)
flexlm_exporter_1           |   /usr/local/go/src/runtime/sema.go:56 +0x39
flexlm_exporter_1           | sync.(*WaitGroup).Wait(0xc000084c60)
flexlm_exporter_1           |   /usr/local/go/src/sync/waitgroup.go:130 +0x64
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect(0xc00055e1e0, 0xc00008b260)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:123 +0x12f
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc000084c54, 0xc00008b260, 0x9c6240, 0xc000190018)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
flexlm_exporter_1           | created by github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x302
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 3446 [runnable]:
flexlm_exporter_1           | regexp.(*inputString).step(0xc000130e58, 0x50, 0x3a, 0x1)
flexlm_exporter_1           |   /usr/local/go/src/regexp/regexp.go:299 +0xc0
flexlm_exporter_1           | regexp.(*machine).tryBacktrack(0xc000130d80, 0xc000111560, 0x9ca200, 0xc000130e58, 0x1, 0x0, 0x724e5b)
flexlm_exporter_1           |   /usr/local/go/src/regexp/backtrack.go:205 +0xbf1
flexlm_exporter_1           | regexp.(*machine).backtrack(0xc000130d80, 0x9ca200, 0xc000130e58, 0x0, 0x54, 0xa, 0x0)
flexlm_exporter_1           |   /usr/local/go/src/regexp/backtrack.go:322 +0x149
flexlm_exporter_1           | regexp.(*Regexp).doExecute(0xc0001bb540, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001576e0, 0x54, 0x0, 0xa, ...)
flexlm_exporter_1           |   /usr/local/go/src/regexp/exec.go:440 +0x318
flexlm_exporter_1           | regexp.(*Regexp).FindStringSubmatch(0xc0001bb540, 0xc0001576e0, 0x54, 0xd, 0xc00007f8e8, 0xc0001576e0)
flexlm_exporter_1           |   /usr/local/go/src/regexp/regexp.go:955 +0xb5
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.parseLmstatLicenseInfoFeature(0xc0003e9000, 0x174, 0x200, 0xc000291e60, 0x3, 0x3)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:202 +0x534
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).getLmstatLicensesInfo(0xc0000ac400, 0xc00008b260, 0x0, 0x0)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:312 +0xa9b
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).Update(0xc0000ac400, 0xc00008b260, 0xd3afa0, 0x43e6d9)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat.go:87 +0xce
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.execute(0x93b921, 0x6, 0x9c4060, 0xc0000ac400, 0xc00008b260)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:128 +0x7e
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect.func1(0xc00008b260, 0xc000084c60, 0x93b921, 0x6, 0x9c4060, 0xc0000ac400)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:119 +0x53
flexlm_exporter_1           | created by github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:118 +0x109
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 3421 [semacquire]:
flexlm_exporter_1           | sync.runtime_Semacquire(0xc00019cdc8)
flexlm_exporter_1           |   /usr/local/go/src/runtime/sema.go:56 +0x39
flexlm_exporter_1           | sync.(*WaitGroup).Wait(0xc00019cdc0)
flexlm_exporter_1           |   /usr/local/go/src/sync/waitgroup.go:130 +0x64
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect(0xc000553950, 0xc00008bda0)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:123 +0x12f
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc00019cdb4, 0xc00008bda0, 0x9c6240, 0xc0000882d0)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x61
flexlm_exporter_1           | created by github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x302
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 3184 [chan receive]:
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc0000ac440, 0x0, 0x0, 0x0, 0x0, 0x0)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:455 +0x4fa
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.Gatherers.Gather(0xc00000a5a0, 0x2, 0x2, 0xc0000ac4c0, 0x8000102, 0x8, 0xffffffffffffffff, 0xc00000a5e0)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:596 +0xc3c
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x9c8d40, 0xc0002480e0, 0xc00010c200)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:82 +0x49
flexlm_exporter_1           | net/http.HandlerFunc.ServeHTTP(0xc0000ac4c0, 0x9c8d40, 0xc0002480e0, 0xc00010c200)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:1964 +0x44
flexlm_exporter_1           | main.handler(0x9c8d40, 0xc0002480e0, 0xc00010c200)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/flexlm_exporter.go:72 +0x7c8
flexlm_exporter_1           | net/http.HandlerFunc.ServeHTTP(0x960bd8, 0x9c8d40, 0xc0002480e0, 0xc00010c200)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:1964 +0x44
flexlm_exporter_1           | net/http.(*ServeMux).ServeHTTP(0xd3aba0, 0x9c8d40, 0xc0002480e0, 0xc00010c200)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:2361 +0x127
flexlm_exporter_1           | net/http.serverHandler.ServeHTTP(0xc00018b040, 0x9c8d40, 0xc0002480e0, 0xc00010c200)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:2741 +0xab
flexlm_exporter_1           | net/http.(*conn).serve(0xc0001ba000, 0x9c9440, 0xc000057400)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:1847 +0x646
flexlm_exporter_1           | created by net/http.(*Server).Serve
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:2851 +0x2f5
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 3451 [chan receive]:
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc0000aca80, 0x0, 0x0, 0x0, 0x0, 0x0)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:455 +0x4fa
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.Gatherers.Gather(0xc00053ed00, 0x2, 0x2, 0xc0000acac0, 0x5000105, 0x8, 0xffffffffffffffff, 0xc00053ed20)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:596 +0xc3c
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x9c8d40, 0xc0002482a0, 0xc00010c400)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:82 +0x49
flexlm_exporter_1           | net/http.HandlerFunc.ServeHTTP(0xc0000acac0, 0x9c8d40, 0xc0002482a0, 0xc00010c400)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:1964 +0x44
flexlm_exporter_1           | main.handler(0x9c8d40, 0xc0002482a0, 0xc00010c400)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/flexlm_exporter.go:72 +0x7c8
flexlm_exporter_1           | net/http.HandlerFunc.ServeHTTP(0x960bd8, 0x9c8d40, 0xc0002482a0, 0xc00010c400)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:1964 +0x44
flexlm_exporter_1           | net/http.(*ServeMux).ServeHTTP(0xd3aba0, 0x9c8d40, 0xc0002482a0, 0xc00010c400)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:2361 +0x127
flexlm_exporter_1           | net/http.serverHandler.ServeHTTP(0xc00018b040, 0x9c8d40, 0xc0002482a0, 0xc00010c400)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:2741 +0xab
flexlm_exporter_1           | net/http.(*conn).serve(0xc0001ba280, 0x9c9440, 0xc0000ac900)
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:1847 +0x646
flexlm_exporter_1           | created by net/http.(*Server).Serve
flexlm_exporter_1           |   /usr/local/go/src/net/http/server.go:2851 +0x2f5
flexlm_exporter_1           |
flexlm_exporter_1           | goroutine 3420 [semacquire]:
flexlm_exporter_1           | sync.runtime_Semacquire(0xc00019cdb4)
flexlm_exporter_1           |   /usr/local/go/src/runtime/sema.go:56 +0x39
flexlm_exporter_1           | sync.(*WaitGroup).Wait(0xc00019cdb4)
flexlm_exporter_1           |   /usr/local/go/src/sync/waitgroup.go:130 +0x64
flexlm_exporter_1           | github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1(0xc00019cdb4, 0xc00008bda0)
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:427 +0x2b
flexlm_exporter_1           | created by github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
flexlm_exporter_1           |   /go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:426 +0x265
grafanaandfriends_flexlm_exporter_1 exited with code 2

```

**Comment by DarkRider1768** [comment]
[root@ehs-docker-01 staging]# docker attach f795c83537cf
panic: assignment to entry in nil map

goroutine 4895 [running]:
github.com/mjtrangoni/flexlm_exporter/collector.parseLmstatLicenseInfoFeature(0xc00035b000, 0x177, 0x200, 0xc000493a70, 0x3, 0x3)
        /go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:212 +0x761
github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).getLmstatLicensesInfo(0xc000316740, 0xc000067740, 0x0, 0x0)
        /go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:312 +0xa9b
github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).Update(0xc000316740, 0xc000067740, 0xd3afa0, 0x43e6d9)
        /go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat.go:87 +0xce
github.com/mjtrangoni/flexlm_exporter/collector.execute(0x93b921, 0x6, 0x9c4060, 0xc000316740, 0xc000067740)
        /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:128 +0x7e
github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect.func1(0xc000067740, 0xc000514de0, 0x93b921, 0x6, 0x9c4060, 0xc000316740)
        /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:119 +0x53
created by github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect
        /go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:118 +0x109
[root@ehs-docker-01 staging]#

**Comment by mjtrangoni** [comment]
@DarkRider1768 sorry for the delay. I need more information from your side. 
Could you please tell me how are you running it?
Are the FlexLM servers available inside the container? 
Is the `flexlm_exporter` working standalone outside a container?

**Comment by mjtrangoni** [comment]
@DarkRider1768 closing this issue for the time. Please feel free to reopen if needed.
