### ISSUE TITLE
exporter falling over with: "fatal error: concurrent map writes"

### ISSUE THREAD

**Issue by daveoy** [mjtrangoni/flexlm_exporter#20]
### Host operating system: output of `uname -a`
docker 2:1.13.1-103.git7f2769b.el7.centos running on Linux <servername> 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### flexlm_exporter version: output of `flexlm_exporter --version`
mjtrangoni/flexlm_exporter:master
### flexlm_exporter command line flags and relevant YAML configuration file information

```
docker run --name flexlm_exporter -p 9319:9319 --volume /opt/flexnetserver/:/usr/bin/flexlm/ --volume /opt/flexlm_exporter/:/config mjtrangoni/flexlm_exporter:master --path.lmutil="/usr/bin/flexlm/lmutil" --path.config="/config/config.yaml"

```
### Are you running flexlm_exporter in Docker?
yes
### What did you do that produced an error?
start exporter, hit the url http://servername:9319/metrics, shortly after, server dies
### What did you expect to see?
expected to refresh the page and get a new set of metrics
### What did you see instead?
'this site can not be reached'

docker run output:
```
time="2019-12-30T21:18:51Z" level=info msg="Starting flexlm_exporter (version=0.0.4, branch=master, revision=c7bd0f5263ed02b4f16ef63a463183dd4c01ed74)" source="flexlm_exporter.go:93"
time="2019-12-30T21:18:51Z" level=info msg="Build context (go=go1.13.5, user=circleci@3208b69c8ce8, date=20191220-19:55:42)" source="flexlm_exporter.go:94"
time="2019-12-30T21:18:51Z" level=info msg="Enabled collectors:" source="flexlm_exporter.go:102"
time="2019-12-30T21:18:51Z" level=info msg=" - lmstat_feature_exp" source="flexlm_exporter.go:105"
time="2019-12-30T21:18:51Z" level=info msg=" - lmstat" source="flexlm_exporter.go:105"
time="2019-12-30T21:18:51Z" level=info msg="Loading license config file:" source="config.go:45"
time="2019-12-30T21:18:51Z" level=info msg=" - /config/tokenflex-chi.yaml" source="config.go:46"
time="2019-12-30T21:18:51Z" level=info msg="Listening on :9319" source="flexlm_exporter.go:128"
fatal error: concurrent map writes

goroutine 39 [running]:
runtime.throw(0x97e8c9, 0x15)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00033f6c0 sp=0xc00033f690 pc=0x42e192
runtime.mapassign_faststr(0x8d85c0, 0xc00008dbc0, 0xc0003461e9, 0xd, 0x0)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x417 fp=0xc00033f728 sp=0xc00033f6c0 pc=0x412e77
github.com/mjtrangoni/flexlm_exporter/collector.parseLmstatLicenseInfoFeature(0xc00042e000, 0x59e, 0x6aa, 0xc00033fab0, 0x3, 0x3)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:215 +0x2d7 fp=0xc00033f8c8 sp=0xc00033f728 pc=0x862dc7
github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).getLmstatLicensesInfo(0xc000180480, 0xc00018a000, 0x0, 0x0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:350 +0x95a fp=0xc00033fe00 sp=0xc00033f8c8 pc=0x86457a
github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).Update(0xc000180480, 0xc00018a000, 0xd92720, 0x0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat.go:88 +0xcb fp=0xc00033fe58 sp=0xc00033fe00 pc=0x85f8db
github.com/mjtrangoni/flexlm_exporter/collector.execute(0x977f7a, 0x6, 0xa274e0, 0xc000180480, 0xc00018a000)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:140 +0x7e fp=0xc00033ff78 sp=0xc00033fe58 pc=0x85eb2e
github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect.func1(0xc00018a000, 0xc00050a070, 0x977f7a, 0x6, 0xa274e0, 0xc000180480)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:126 +0x53 fp=0xc00033ffb0 sp=0xc00033ff78 pc=0x8651a3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00033ffb8 sp=0xc00033ffb0 pc=0x45a941
created by github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:125 +0x109

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7ff98b984f08, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001e8198, 0x72, 0x0, 0x0, 0x9783e3)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0001e8180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0001e8180, 0xc0002d7bc0, 0x6c5604, 0xc0002100a0)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000d1e0, 0x5e0a69ca, 0xc0002d7bc0, 0x4b9526)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000d1e0, 0xc0002d7c10, 0x18, 0xc000000180, 0x6c4b34)
	/usr/local/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc000210000, 0xa309e0, 0xc00000d1e0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2896 +0x280
net/http.(*Server).ListenAndServe(0xc000210000, 0xc000210000, 0x2)
	/usr/local/go/src/net/http/server.go:2825 +0xb7
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3081
main.main()
	/go/src/github.com/mjtrangoni/flexlm_exporter/flexlm_exporter.go:130 +0xd24

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7ff98b984e38, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001e8218, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001e8200, 0xc000226000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0001e8200, 0xc000226000, 0x1000, 0x1000, 0xc000152000, 0x3030320000000000, 0xed59c60be)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e0e8, 0xc000226000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
net/http.(*connReader).Read(0xc00008da40, 0xc000226000, 0x1000, 0x1000, 0x7ff98dbfaee8, 0xd4b04a, 0x200203000)
	/usr/local/go/src/net/http/server.go:785 +0xf4
bufio.(*Reader).fill(0xc0000aea80)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadSlice(0xc0000aea80, 0xa, 0x7ff98b941438, 0xc0000819a8, 0x40bda6, 0xc0001e2000, 0x100)
	/usr/local/go/src/bufio/bufio.go:359 +0x3d
bufio.(*Reader).ReadLine(0xc0000aea80, 0xc0000819b0, 0xc000360380, 0x7ff98dbf2b28, 0x0, 0x40c618, 0x30)
	/usr/local/go/src/bufio/bufio.go:388 +0x34
net/textproto.(*Reader).readLineSlice(0xc00008c810, 0xc0001e2000, 0xc0001e8200, 0x0, 0x0, 0x10000004b8c2d)
	/usr/local/go/src/net/textproto/reader.go:57 +0x6c
net/textproto.(*Reader).ReadLine(...)
	/usr/local/go/src/net/textproto/reader.go:38
net/http.readRequest(0xc0000aea80, 0x0, 0xc0001e2000, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:1012 +0x92
net/http.(*conn).readRequest(0xc000222000, 0xa322a0, 0xc0000b0a00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:965 +0x15f
net/http.(*conn).serve(0xc000222000, 0xa322a0, 0xc0000b0a00)
	/usr/local/go/src/net/http/server.go:1817 +0x6d4
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x7ff98b984d68, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001e8298, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001e8280, 0xc000224000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0001e8280, 0xc000224000, 0x1000, 0x1000, 0xc0000263c0, 0xc0000877e8, 0x6b9f53)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e0f0, 0xc000224000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
net/http.(*connReader).Read(0xc00001f020, 0xc000224000, 0x1000, 0x1000, 0x0, 0x3540, 0x203000)
	/usr/local/go/src/net/http/server.go:785 +0xf4
bufio.(*Reader).fill(0xc00006a780)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadSlice(0xc00006a780, 0xa, 0x28, 0xc0000879a8, 0x40bda6, 0xc0001e2200, 0x100)
	/usr/local/go/src/bufio/bufio.go:359 +0x3d
bufio.(*Reader).ReadLine(0xc00006a780, 0x10, 0xd93320, 0x7ff98dbf1008, 0x0, 0x40c618, 0x30)
	/usr/local/go/src/bufio/bufio.go:388 +0x34
net/textproto.(*Reader).readLineSlice(0xc00001f080, 0xc0001e2200, 0xc0001e8280, 0x0, 0x0, 0x7ff98b942070)
	/usr/local/go/src/net/textproto/reader.go:57 +0x6c
net/textproto.(*Reader).ReadLine(...)
	/usr/local/go/src/net/textproto/reader.go:38
net/http.readRequest(0xc00006a780, 0x0, 0xc0001e2200, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:1012 +0x92
net/http.(*conn).readRequest(0xc0002220a0, 0xa322a0, 0xc000026300, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:965 +0x15f
net/http.(*conn).serve(0xc0002220a0, 0xa322a0, 0xc000026300)
	/usr/local/go/src/net/http/server.go:1817 +0x6d4
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384

goroutine 37 [semacquire]:
sync.runtime_Semacquire(0xc00050a068)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00050a060)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1(0xc00050a060, 0xc00018a000)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:427 +0x2b
created by github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:426 +0x24c

goroutine 54 [chan receive]:
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc000180500, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:455 +0x4f5
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.Gatherers.Gather(0xc0005692a0, 0x2, 0x2, 0xc000257808, 0x0, 0x0, 0xc000569260, 0x0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:596 +0xc0d
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0xa30ca0, 0xc0002341c0, 0xc0001e2500)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:82 +0x4c
net/http.HandlerFunc.ServeHTTP(0xc000180540, 0xa30ca0, 0xc0002341c0, 0xc0001e2500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
main.handler(0xa30ca0, 0xc0002341c0, 0xc0001e2500)
	/go/src/github.com/mjtrangoni/flexlm_exporter/flexlm_exporter.go:76 +0x6cc
net/http.HandlerFunc.ServeHTTP(0x99d0b0, 0xa30ca0, 0xc0002341c0, 0xc0001e2500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xd925e0, 0xa30ca0, 0xc0002341c0, 0xc0001e2500)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc000210000, 0xa30ca0, 0xc0002341c0, 0xc0001e2500)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000b23c0, 0xa322a0, 0xc0001801c0)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384

goroutine 32 [chan receive]:
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc0001803c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:455 +0x4f5
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.Gatherers.Gather(0xc0001b63c0, 0x2, 0x2, 0xc000259808, 0x0, 0x0, 0xc0001b6380, 0x0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:596 +0xc0d
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0xa30ca0, 0xc0002100e0, 0xc0001e2100)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:82 +0x4c
net/http.HandlerFunc.ServeHTTP(0xc000180400, 0xa30ca0, 0xc0002100e0, 0xc0001e2100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
main.handler(0xa30ca0, 0xc0002100e0, 0xc0001e2100)
	/go/src/github.com/mjtrangoni/flexlm_exporter/flexlm_exporter.go:76 +0x6cc
net/http.HandlerFunc.ServeHTTP(0x99d0b0, 0xa30ca0, 0xc0002100e0, 0xc0001e2100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xd925e0, 0xa30ca0, 0xc0002100e0, 0xc0001e2100)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc000210000, 0xa30ca0, 0xc0002100e0, 0xc0001e2100)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001861e0, 0xa322a0, 0xc000180000)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384

goroutine 55 [IO wait]:
internal/poll.runtime_pollWait(0x7ff98b984bc8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0000f2498, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f2480, 0xc00008d091, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0000f2480, 0xc00008d091, 0x1, 0x1, 0xc000026418, 0xc000504f68, 0x47470c)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0001580d0, 0xc00008d091, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
net/http.(*connReader).backgroundRead(0xc00008d080)
	/usr/local/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:673 +0xd4

goroutine 16 [semacquire]:
sync.runtime_Semacquire(0xc0002c2688)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0002c2680)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1(0xc0002c2680, 0xc0000ae6c0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:427 +0x2b
created by github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:426 +0x24c

goroutine 97 [semacquire]:
sync.runtime_Semacquire(0xc0002c2698)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0002c2690)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect(0xc00008d5f0, 0xc0000ae6c0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:131 +0x12f
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc0002c2680, 0xc0000ae6c0, 0xa2bda0, 0xc0000ac040)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x6b
created by github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x2e9

goroutine 70 [IO wait]:
internal/poll.runtime_pollWait(0x7ff98b9846e8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001e8098, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001e8080, 0xc00008d2a1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0001e8080, 0xc00008d2a1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000ac030, 0xc00008d2a1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
net/http.(*connReader).backgroundRead(0xc00008d290)
	/usr/local/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:673 +0xd4

goroutine 98 [runnable]:
regexp.(*inputString).step(0xc000384130, 0xb, 0xffffffff00000036, 0x1)
	/usr/local/go/src/regexp/regexp.go:365 +0xbc
regexp.(*Regexp).tryBacktrack(0xc000186dc0, 0xc0003840b0, 0xa33a20, 0xc000384130, 0xc000000001, 0x0, 0x0)
	/usr/local/go/src/regexp/backtrack.go:227 +0xa55
regexp.(*Regexp).backtrack(0xc000186dc0, 0x0, 0x0, 0x0, 0xc000310ea0, 0x5b, 0x0, 0x0, 0xdaef00, 0x0, ...)
	/usr/local/go/src/regexp/backtrack.go:326 +0x17d
regexp.(*Regexp).doExecute(0xc000186dc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000310ea0, 0x5b, 0x0, 0x0, ...)
	/usr/local/go/src/regexp/exec.go:535 +0x453
regexp.(*Regexp).doMatch(...)
	/usr/local/go/src/regexp/exec.go:514
regexp.(*Regexp).MatchString(...)
	/usr/local/go/src/regexp/regexp.go:507
github.com/mjtrangoni/flexlm_exporter/collector.parseLmstatLicenseInfoFeature(0xc000400000, 0x59e, 0x6aa, 0xc0002d9ab0, 0x3, 0x3)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:198 +0x163
github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).getLmstatLicensesInfo(0xc000180340, 0xc0000ae6c0, 0x0, 0x0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat_linux.go:350 +0x95a
github.com/mjtrangoni/flexlm_exporter/collector.(*lmstatCollector).Update(0xc000180340, 0xc0000ae6c0, 0xd92720, 0x0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/lmstat.go:88 +0xcb
github.com/mjtrangoni/flexlm_exporter/collector.execute(0x977f7a, 0x6, 0xa274e0, 0xc000180340, 0xc0000ae6c0)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:140 +0x7e

▽
github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect.func1(0xc0000ae6c0, 0xc0002c2690, 0x977f7a, 0x6, 0xa274e0, 0xc000180340)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:126 +0x53
created by github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:125 +0x109

goroutine 38 [semacquire]:
sync.runtime_Semacquire(0xc00050a078)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00050a070)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/mjtrangoni/flexlm_exporter/collector.FlexlmCollector.Collect(0xc00001e210, 0xc00018a000)
	/go/src/github.com/mjtrangoni/flexlm_exporter/collector/collector.go:131 +0x12f
github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc00050a060, 0xc00018a000, 0xa2bda0, 0xc000440018)
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x6b
created by github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/src/github.com/mjtrangoni/flexlm_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x2e9
```

**Comment by daveoy** [comment]
some more information:

looks like reloading the http page works fine, but when prometheus tries to scrape the page, that's when it dies.

**Comment by daveoy** [comment]
some new info, this appears to die not when a user loads the webpage (which totally works) but actually when prometheus scrapes the page.

**Comment by knweiss** [comment]
It's easy to reproduce this issue: Build with `go build -race`and then start multiple metric scrapes in parallel.

The Go runtime will log many `WARNING: DATA RACE` warnings with explanations. They all happen at the writes to the package-level map variables in `collector/lmstat_{linux,windows}.go`.

**Comment by mjtrangoni** [comment]
@daveoy thanks for reporting. I am currently on vacation, but I will take a look as soon as possible.

**Comment by mjtrangoni** [comment]
@daveoy can you please check if this works for you? @knweiss fixed some race conditions

**Comment by daveoy** [comment]
```
[root@flexlmserver ~]# docker pull mjtrangoni/flexlm_exporter:master
Trying to pull repository docker.io/mjtrangoni/flexlm_exporter ...
master: Pulling from docker.io/mjtrangoni/flexlm_exporter
ab5ef0e58194: Pull complete
80efde3cb63c: Pull complete
da293244aea6: Pull complete
Digest: sha256:49eaea269994acc1e45a2cd429b31a7951262624a8301cc7e23426e34fea65dd
Status: Downloaded newer image for docker.io/mjtrangoni/flexlm_exporter:master
[root@flexlmserver exporter_config]# docker run --name flexlm_exporter -d -p 9319:9319 --volume /opt/flexnetserver/:/usr/bin/flexlm/ --volume /root/exporter_config/:/config mjtrangoni/flexlm_exporter:master --path.lmutil="/usr/bin/flexlm/lmutil" --path.config="/config/flexlmserver.yaml"
cf4dee4e7072eb62250b7d5ec5a5857d125e34f223df2120323e2ba073e9173b
[root@tokenflex-ny exporter_config]# docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                    NAMES
cf4dee4e7072        mjtrangoni/flexlm_exporter:master   "/bin/flexlm_expor..."   3 seconds ago       Up 2 seconds        0.0.0.0:9319->9319/tcp   flexlm_exporter
[root@tokenflex-ny exporter_config]# docker image list
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
docker.io/mjtrangoni/flexlm_exporter   master              67496ecbe146        31 minutes ago      296 MB
```
confirmed metrics are showing in prometheus and exporter is still up

great work all, thanks for the help
